### PR TITLE
ink_2e2 event decode

### PR DESCRIPTION
**Pull request by ganesh1997oli**
Add event decode testing for unit test and e2e_test as per discussion by @alessandro-baldassarre and @blairmunroakusa

### CODE REVIEW

**Comment by blairmunroakusa** [comment]
This PR is still somewhat WIP at moment, waiting on PR [https://github.com/ganesh1233456/ink-examples/pull/1](https://github.com/ganesh1233456/ink-examples/pull/1) introducing improvements on presentation and testing capabilities, including README.

**Comment by blairmunroakusa** [comment]
Cla signed, and PR no longer WIP.

**Review by ascjones — COMMENTED** [review]
Perhaps this belongs better in https://github.com/paritytech/ink/tree/master/integration-tests?

I believe the idea for this repo is to have "real world" examples, whereas `ink/integration-tests` contains more feature specific "examples".

**Comment by blairmunroakusa** [comment]
@ascjones I like the sounds of that much better!

I will open PR there, unless you have any other insights/suggestions.

**Pull request closed without merging**
